### ISSUE TITLE
Please provide attribution

### ISSUE THREAD

**Issue by Sentdex** [kamalhaddad/BeginnerMachineLearning#1]
Hello, your KNN code looks like it came from my tutorials on https://PythonProgramming.net & https://Youtube.com/sentdex

Original source to cite: https://pythonprogramming.net/programming-k-nearest-neighbors-machine-learning-tutorial/

Thanks,
Sentdex

**Comment by kamalhaddad** [comment]
Yes, that's right! My apologies was going to take this repo down. My apologies.
